Revert "fix(board): resolve TypeError: O is not a function by refactoring useStore selectors and adding thumbnail guards. Bump version to 2.1.3."
This reverts commit 2394583ef9dba7f82894464431f1e0b94695bdab.